version: '3'
services:
  web-frontend:
    image: pabmen/tenis-front
    environment:
      PORT: 3000
      PROXY_API: http://web-backend:8080/
    ports:
      - 80:3000
  web-backend:
    image: pabmen/tenis-back
    ports:
      - 4000:4000

  # RUN THIS COMPOSE
  # docker-compose -f docker-compose.yml up