version: '3'
services:
  web-frontend:
    image: web-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://web-backend:8080/
    ports:
      - 3000:3000
  web-backend:
    image: web-backend:latest
    ports:
      - 4000:4000

  # RUN THIS COMPOSE
  # docker-compose -f docker-compose.yml up